name: Build and check formatting.
on:
  push:
    branches: ['main']
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install NPM dependencies
        run: npm install --force
      - name: Build project
        run: npm run build
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install NPM dependencies
        run: npm install --force
      - run: npm run format-check
